more debugging in configure.log [temporary]   (calls ldd to debug dependencies for [future] static support)
$_ld_x11 contains now $_ld_sock

improved x11 C test

libGL is no longer OS dependent (bsd) but depends on 2 compil' tests

preliminary support for -static:
  -static requires any test succeeds with that flag
  missing -logg for vorbis (triggered by -static)

NB: It still can't compile in static [undefined reference to... errors :/ ]


git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@2989 b3059339-0415-0410-9bf9-f77b7e298cf2