Remove '.section' causing the following assembler error on OS/2.
    Error: unknown pseudo-op: `.section'


git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@30511 b3059339-0415-0410-9bf9-f77b7e298cf2